# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define "test01" do |test01|
    test01.vm.box = "jeqo/centos-7"

    test01.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = "512"
    end

    test01.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "test.yml"
      ansible.galaxy_role_file = "roles.yml"
      ansible.extra_vars = {
        elasticsearch_major: "2.x",
        elasticsearch_cluster_name: "es_cluster",
        elasticsearch_node_name: "es_node01",
      }
    end
  end
end
